name: Bug Report
description: Report a bug or issue with MCP Fixer Server
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Run command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - macOS 12 (Monterey)
        - macOS 13 (Ventura)
        - macOS 14 (Sonoma)
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Other Linux
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running? (run `node --version`)
      placeholder: e.g. v18.17.0
    validations:
      required: true

  - type: input
    id: claude-version
    attributes:
      label: Claude Desktop Version
      description: What version of Claude Desktop are you using?
      placeholder: e.g. 0.9.1

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      render: shell
      placeholder: Paste error logs here...

  - type: textarea
    id: diagnostic-output
    attributes:
      label: Diagnostic Output
      description: If possible, run "Claude, generate a diagnostic report" and paste the output
      render: json
      placeholder: Paste diagnostic output here...

  - type: checkboxes
    id: attempted-solutions
    attributes:
      label: Attempted Solutions
      description: What have you already tried?
      options:
        - label: Restarted Claude Desktop
        - label: Checked configuration syntax
        - label: Verified dependencies are installed
        - label: Checked for port conflicts
        - label: Reviewed logs for errors

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have provided all required information
          required: true
        - label: I have removed sensitive information from logs/config
          required: true